Detodotrabajo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static 
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]
if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),
    ]

app/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static 
from. import views

urlpatterns = [
    path('', views.app, name='app'),
    path('userNew/', views.usuario_new, name='newUser'),
    #path('login/', LoginView.as_view(template_name='app/login.html'), name='login'),
    path('login/', views.Login.as_view(), name='login'),
	path('logout/', LogoutView.as_view(), name='logout'),
    path('myaccount/', views.myaccount, name='myaccount'),
    path('Edit/', views.User_edit.as_view(), name='Edit_User'),
    path('UploadImageU/', views.upload_image_User_view, name='UploadImageUser'),
    path('CreateHabili/', views.Create_habili.as_view(), name='CreateHabili'),
    path('HabilidadEdit/<int:id>/', views.Habili_edit, name='Habili_edit'),
    path('HabilidadDelete/<int:id>/', views.Habili_delete, name='Habili_delete'),
    path('Perfil/<int:id>/', views.Busquedaanuncio, name='Perfil_list'),
    path('Resultado/', views.Busqueda.as_view(), name='busqueda'),
    path('Favorito/', views.Favorito, name='Favorite'),
    path('SolicitudPedido/', views.Realizar_Pedido, name='SoliPedidos'),
    path('Pedidos/', views.Pedidos.as_view(), name='Pedidos'),
    path('Aceptar_Solicitud/', views.AceptarSolicitud, name='AceptarSolicitud'),
    path('Cancelar_Solicitud/', views.CancelarSolicitud, name='CancelarSolicitud'),
    path('DetallePedido/<int:id>/', views.Detalle_Pedido, name='Detalle_Pedido'),
    
    path('Valoracion_Solicitud/<int:id>/', views.Valorizacion_Pedido, name='Valorizacion_Pedido'),

    ] 

app/forms.py
import email
from email.mime import image
from multiprocessing.sharedctypes import Value
from pyexpat import model
import re
from statistics import mode
from sys import maxsize
from xml.dom.minidom import Attr
from django import forms
from django.forms import HiddenInput, fields
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.views.generic.edit import UpdateView
from django.core.validators import MinValueValidator, MaxValueValidator
from bootstrap_modal_forms.forms import BSModalModelForm 
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
from django.contrib.auth import get_user_model
from .models import *

User =get_user_model()
class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Username','required': True,'autofocus' : True}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password','required': True}))
    remember_me = forms.BooleanField(required=False)

class UserRegisterForm(UserCreationForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Username','required': True,'autofocus' : True}))
	email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Username','required': True}))
	password1 = forms.CharField(label='Contraseña',help_text='Debe contener MAYUSCULAS, minusculas y numero, minimo 9 caracteres', widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password','required': True}))
	password2 = forms.CharField(label='Confirma Contraseña', widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password','required': True}))

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']
		
	def clean(self):
		# data from the form is fetched using super function
		super(UserRegisterForm, self).clean()
		# extract the username and text field from the data
		username = self.cleaned_data.get('username')
		email = self.cleaned_data.get('email')
		# conditions to be met for the username length
		#if len(username) < 5:
		#	self._errors['username'] = self.error_class(['Mínimo 5 caracteres requeridos'])
			
		#if User.objects.filter(username=username).exists():
		#	self._errors['email'] = self.error_class(['El usuario ya se encuentra registrado'])	

		if User.objects.filter(email=email).exists():
			self._errors['email'] = self.error_class(['Ya existe este correo registrado porfavor ingrese otro.'])

		# return any errors if found
		return self.cleaned_data

class UserEditForm(BSModalModelForm):
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	telefono = forms.IntegerField(required=True, widget= forms.TextInput(attrs={'class':'form-control'}))
	dni = forms.IntegerField(required=True, widget= forms.TextInput(attrs={'class':'form-control'}))
	Direcion = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control'}))

	distrito = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control'}))
	provincia = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control'}))
	departamento = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control'}))
	pais = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control'}))

	class Meta:
		model = User
		fields = ['first_name','last_name','telefono', 'dni', 'Direcion','distrito','provincia', 'departamento', 'pais']
	def clean(self):
		# data from the form is fetched using super function
		super(UserEditForm, self).clean()
		# extract the username and text field from the data
		dni = self.cleaned_data.get('dni')
		telefono = self.cleaned_data.get('telefono')

		DNI_string = str(dni)
		DNilength = len(DNI_string)
		Tele_string = str(telefono)
		telelength = len(Tele_string)
		print(DNI_string)
		# conditions to be met for the username length
		if DNilength >= 9:
			self._errors['dni'] = self.error_class(['El DNI no puede ser mayor de 8 dijitos'])
		elif DNilength <=7 :
			self._errors['dni'] = self.error_class(['El DNI no puede ser menor de 8 dijitos'])
		elif DNilength == 0 :
			self._errors['dni'] = self.error_class(['El DNI no puede estar vacio'])

		if telelength > 10:
			self._errors['telefono'] = self.error_class(['El DNI no puede ser mayor de 10 dijitos'])

		# return any errors if found
		return self.cleaned_data


class UploadImageusaerForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['imagen']

class habilidadesfrom (BSModalModelForm):

	nombrehabilidad = forms.CharField(required=True,max_length=50, widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'Ingrese su habilidad',"aria-describedby":"id_nombrehabilidad"}))
	descripcion = forms.CharField(max_length=1000,widget=forms.Textarea(attrs={'class': 'form-control','placeholder':'Ingrese su descripcion','style':'height: 150px'}))
	tipoTrabajo = forms.ModelChoiceField(queryset=TipoTrabajo.objects.all(), initial='Seleccione un tipo de trabajo', widget=forms.Select(attrs={'class': 'form-select'}))
	class Meta:
		model = Habilidades
		fields =['nombrehabilidad','tipoTrabajo','descripcion']

class habilidadesFullForm(habilidadesfrom,BSModalModelForm):
	images = forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control','multiple': True,'id':'seleccionArchivos'}))

	class Meta(habilidadesfrom.Meta):
		fields = habilidadesfrom.Meta.fields + ['images',]


class Valoracionfrom (forms.ModelForm):

	comentario = forms.CharField(max_length=1000,widget=forms.Textarea(attrs={'class': 'form-control','placeholder':'Ingrese su descripcion','style':'height: 100px'}))
	puntuacion = forms.CharField(required=False, widget=forms.HiddenInput(attrs={'class': 'result'}))

	class Meta:
		model = Clasifiacion
		fields =['comentario','puntuacion']

class ValoracionFullForm(Valoracionfrom):

	fotoValoracion = forms.FileField(required=False,widget=forms.ClearableFileInput(attrs={'class': 'form-control','multiple': True,'id':'seleccionArchivos'}))

	class Meta(Valoracionfrom.Meta):
		fields = Valoracionfrom.Meta.fields + ['fotoValoracion']

app/templates/app/Busqueda.html
{% extends "app/layout.html" %}
{% load Filtrospersonalizado %}
{% block content %}
<section class="py-2">
  <div class="container px-3 my-2">
      <div class="row gx-5">
          <div class="col-lg-12 px-3 my-2">
            <section class="py-5">
              <div class="container px-2 my-2">
                <article>
                  <!-- Post header-->
                  <header class="mb-4">
                      <!-- Post title-->
                      <h1 class="fw-bolder mb-1">Busqueda "{{valor}}"</h1>
                      <form class="d-flex flex-row-reverse bd-highlight" method="GET">
                        <div class="d-flex flex-row-reverse bd-highlight">
                          <input type="hidden" name="busqueda" value="{{valor}}"></input>
                          <select  class="form-select bd-highlight" name="browse" onchange="this.form.submit()">
                              <option value="0">Mayor a Menor Valorado </option>
                              <option value="2">Mayor a Menor Valorado </option>
                              <option value="3">Mayor a Menor Pedidos </option>
                              <option value="4">Mayor a Menor Pedidos </option>
                          </select>
                        </div>
                        
                      </form>
                  </header>
                  <!-- Preview image figure-->
                </article>

                  <div class="row gx-2 row-cols-1 row-cols-sm-2 row-cols-xl-4">
                    {% for Ha in habilidades %}
                    <div class="col-lg-4 mb-5">
                      <div class="card h-100 shadow border-0">
                          <div class="carousel slide card-img-top" data-bs-ride="carousel">
                            <div class="carousel-inner">
                              {% for foto in Ha.id|existing_Fototrabajo %}
                              {% get_active forloop.counter0 as dato%}
                              <div class="carousel-item {{ dato }}">
                                <img src="{{foto.fotoTrabajo.url}}" class="d-block w-100" alt="...">
                              </div>
                              {% empty %}
                              <div class="carousel-item active">
                                <img src="https://dummyimage.com/600x500/ced4da/6c757d&text=Sin+Imagen" alt="...">
                              </div>
                              {% endfor %}
                            </div>
                          </div>
                          <div class="card-body p-4">
                              <div class="badge bg-primary bg-gradient rounded-pill mb-2">{{ Ha.tipoTrabajo.tipotrabajo }}</div>
                              <a class="text-decoration-none link-dark stretched-link" href="{% url 'Perfil_list' Ha.id %}"><h5 class="card-title mb-3 text-capitalize">{{Ha.nombrehabilidad}}</h5></a>
                              <p class="card-text mb-0 truncate-2">{{Ha.descripcion}}</p>
                          </div>
                          <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                              <div class="d-flex align-items-end justify-content-between">
                                  <div class="d-flex align-items-center">
                                      <img class="rounded-circle me-3 imgCard" src="{{Ha.user.imagen.url}}" alt="..." />
                                      <div class="small">
                                          
                                          <div class="">
                                            {% if Ha.user.first_name|length == 0 or  Ha.user.last_name|length == 0 %}
                                            <div class="fw-bold text-capitalize">{{ Ha.user.username }}</div>
                                            {% else %}
                                            <div class="fw-bold text-capitalize">{{ Ha.user.first_name }} {{ Ha.user.last_name }}</div>
                                            {% endif %}
                                            <span><i class="fas fa-comment-alt Comentario"></i>624</span>
                                            <span><i class="fa-solid fa-star StarValoration "></i>4.5</span>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>

                    {% empty %}
                      <div class="fa-2x">
                        <span  style="display: inline-block;">
                          <i class="fa-solid fa-xmark"></i> Sin resultados
                        </span>
                      </div>
                    {% endfor %}
                  </div>
                    
                  {% if is_paginated %}
                    <nav aria-label="Page navigation example">
                      <ul class="pagination justify-content-end">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                          <a class="page-link" href="{% url 'busqueda' %}?busqueda={{valor}}&page={{ page_obj.previous_page_number }}">Previous</a>
                        </li>
                        {% endif %}

                        {% for n in page_obj.paginator.page_range %}
                          {% if page_obj.number == n %}
                          <li class="page-item active"><span class="page-link">{{ n }}</span></li>
                          {% elif n > page_obj.number|add:'-3' and n < page_obj.number|add:'3' %}
                          <li class="page-item">
                            <a class="page-link" href="{% url 'busqueda' %}?busqueda={{valor}}&page={{ n }}{% if parametros.urlencode %}&{{ parametros.urlencode }}{% endif %}">{{ n }}</a>
                          </li>
                          {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                        <li class="page-item">
                          <a class="page-link" href="{% url 'busqueda' %}?busqueda={{valor}}&page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                        {% endif %}
                      </ul>
                    </nav>
                  {% endif %}

              </div>
            </section>
          </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/app/Create-Habilidad.html
{% load widget_tweaks %}
{% load Filtrospersonalizado %}
<form method="post" enctype="multipart/form-data" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Create Book</h3>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
    </button>
  </div>

  <div class="modal-body row g-2">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      {% if not forloop.last%}
      {% get_colum forloop.counter0 6 12 2 as dato%}
        <div class="col-md-{{ dato }}">
          <div class="form-floating">
            {% render_field field class="form-control" placeholder=field.label %}
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          </div>
          <div class="{% if field.errors %} invalid{% endif %}">
            {% for error in field.errors %}
              <p class="help-block">{{ error }}</p>
            {% endfor %}
          </div>
        </div>
      {% else %}
      <div class="input-group mb-3">
        <label class="input-group-text" for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
      </div>
      <div class="{% if field.errors %} invalid{% endif %}">
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
      {% endif %}
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Create</button>
  </div>

</form>

app/templates/app/DetallePedido.html
{% load Filtrospersonalizado %}

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Detalle de la solicitud</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>

<div class="modal-body mb-4 px-4"> 

    <div class="row">
        <div class="col-sm-6">
            <div class="card">
            <div class="card-body">
                <div class="d-flex align-items-center">
                    <img class="rounded-circle me-3 imgCard contain" src="{{Pedido.habilidad.user.imagen.url}}" alt="..." />
                    <div class="small">
                        {% if Pedido.habilidad.user.first_name|length == 0 or  Pedido.habilidad.user.last_name|length == 0 %}
                        <div class="fw-bold">{{ Pedido.habilidad.user.username }}</div>
                        {% else %}
                        <div class="fw-bold">{{ Pedido.habilidad.user.first_name }} {{ Pedido.habilidad.user.last_name }}</div>
                        {% endif %}
                        <div class="text-muted">Puntuacion: 4.9</div>
                    </div>
                </div>
            </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card">
            <div class="card-body">
                <div class="d-flex align-items-center">
                    <img class="rounded-circle me-3 imgCard contain" src="{{Pedido.user.imagen.url}}" alt="..." />
                    <div class="small">
                        {% if Pedido.user.first_name|length == 0 or Pedido.user.last_name|length == 0 %}
                        <div class="fw-bold">{{ Pedido.user.username }}</div>
                        {% else %}
                        <div class="fw-bold">{{ Pedido.user.first_name }} {{ Pedido.user.last_name }}</div>
                        {% endif %}
                        <div class="text-muted">Puntuacion: 4.7</div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>

    <div class="position-relative m-5">
        <div class="progress" style="height: 1px;">
            <div class="progress-bar" role="progressbar" style="width: 33%;" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <button type="button" class="position-absolute top-0 start-0 translate-middle btn btn-sm btn-primary rounded-pill" style="width: 2rem; height:2rem;">1</button>
        <button type="button" class="position-absolute top-0 start-33 translate-middle btn btn-sm btn-primary rounded-pill" style="width: 2rem; height:2rem;">2</button>
        <button type="button" class="position-absolute top-0 start-66 translate-middle btn btn-sm btn-primary rounded-pill" style="width: 2rem; height:2rem;">3</button>
        <button type="button" class="position-absolute top-0 start-100 translate-middle btn btn-sm btn-secondary rounded-pill" style="width: 2rem; height:2rem;">4</button>
    </div>
    <div class="position-relative m-5">
        <div class="position-absolute top-0 start-0 translate-middle text-center small" >
            <div class="fw-bold">Pendiente</div>
            <div class="text-muted">March 23, 2021</div>
        </div>
        <div class="position-absolute top-0 start-33 translate-middle text-center small" >
            <div class="fw-bold">Aceptado</div>
            <div class="text-muted">March 23, 2021</div>
        </div>
        <div class="position-absolute top-0 start-66 translate-middle text-center small" >
            <div class="fw-bold">Realizado</div>
            <div class="text-muted">March 23, 2021</div>
        </div>
        <div class="position-absolute top-0 start-100 translate-middle text-center small" >
            <div class="fw-bold">Finalizado</div>
            <div class="text-muted">March 23, 2021</div>

        </div>
    </div>

</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
</div>

app/templates/app/Edit-Habilidad.html
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Modificar Habilidad</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<form class="form-floating row g-3" method="post" enctype="multipart/form-data" action="{% url 'Habili_edit' idhabilidad  %}">
    {% csrf_token %}
    <div class="modal-body">
      <div class="card" >
        <div class="card-body">
          <div class="row g-2">
            <div class="col-md">
              <div class="form-floating">
                  {{ formhabilidadesEdi.nombrehabilidad }}
                <label for="floatingInputGrid">Ingrese Habilidad</label>
              </div>
            </div>
            <div class="col-md">
              <div class="form-floating">
                  {{ formhabilidadesEdi.tipoTrabajo }}
                <label for="floatingSelectGrid">Tipo de trabajo</label>
              </div>
            </div>
            <div class="form-floating">
              {{ formhabilidadesEdi.descripcion }}
              <label for="floatingTextarea2">Descripcion</label>
            </div>
            <div class="input-group mb-3">
              {{ formhabilidadesEdi.images }}
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      <button type="submit" class="btn btn-primary">Modificar</button>
    </div>
</form>

app/templates/app/Puntuacion.html
{% block Script %}
<script type="text/javascript"> 
    $(function () {
        $(".rateyo").rateYo().on("rateyo.change", function (e, data) {
            var rating = data.rating;
            $(this).parent().find('.result').val(rating);
            $(this).parent().find('.result').text(rating);
        });
    });
</script>
{% endblock %}

app/templates/app/UploadImageusaer.html
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Añadir imagen</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<form class="form-floating row g-3" enctype="multipart/form-data" method="post" action="{% url 'UploadImageUser' %}">
    {% csrf_token %}
    <div class="modal-body">
      <div class="card" >
        <div class="card-body">
          {{ form_user_upload.as_p }}
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      <button type="submit" class="btn btn-primary">Modificar</button>
    </div>      
</form>

app/templates/app/UserNew.html
{% extends "app/layout.html" %}
{% load static %}
{% block content %}
{% load widget_tweaks %}
<section class="py-5">
	<div class="container px-5">
		<div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
			<div class="text-center mb-5">
				<div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="far fa-user"></i></div>
				<h1 class="fw-bolder">Register</h1>
				<p class="lead fw-normal text-muted mb-0">Comienza un nuevo trabajo </p>
			</div>
			<div class="row gx-5 justify-content-center">
				<div class="col-lg-8 col-xl-6">

					<form class="form" method="post">
						{% csrf_token %}

						{% for field in form_user %}

							<div class="form-floating mb-3">
								{% if field.errors %}
								{{ field|add_class:"is-invalid" }}
								{% else %}
								{{ field }}
								{% endif %}

								<label for="floatingInput">{{ field.label_tag }}</label>
							</div>

							<p>
								{% if field.help_text %}
									<small style="color: grey">{{ field.help_text }}</small>
								{% endif %}
								{% for error in field.errors %}
									<p style="color: red">{{ error }}</p>
								{% endfor %}
							</p>
						{% endfor %}



						<button class="btn btn-primary btn-lg action-button px-4 me-sm-3"  type="submit" id="submit">Registar</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}
<section class="py-5">
	<div class="container px-5">
		<div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
			<div class="text-center mb-5">
				<div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="far fa-user"></i></div>
				<h1 class="fw-bolder">Login</h1>
				<p class="lead fw-normal text-muted mb-0">Comienza un nuevo dia </p>
			</div>
			<div class="row gx-5 justify-content-center">
				<div class="col-lg-8 col-xl-6">

					{% if form.errors %}
					<p>Su nombre de usuario y contraseña no coinciden. Inténtalo de nuevo.</p>
					{% endif %}
					{% if next %}
						{% if user.is_authenticated %}
						<p>Su cuenta no tiene acceso a esta página. Para proceder,
							por favor inicie sesión con una cuenta que tenga acceso.</p>
						{% else %}
						<p>Por favor inicie sesión para ver esta página.</p>
						{% endif %}
					{% endif %}
					<form class="form" method="post">
						{% csrf_token %}
						<div class="form-floating mb-3">
							{{ form.username }}
							<label for="floatingInput">Usuario</label>
						</div>
						<div class="form-floating">
							{{ form.password }}
							<label for="floatingPassword">Contraseña</label>
						</div>
						<div class="checkbox mb-3">
							<label for="id_remember_me">
								{{ form.remember_me }} Recordar
							</label>
						</div>
						<button class="btn btn-primary btn-lg px-4 me-sm-3"  type="submit" id="submit">Login</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

app/templates/app/prueba.html
{% extends "app/layout.html" %}

{% block content %}

<section class="py-2">
    <div class="container px-2">
        <div class="row gx-5 align-items-center justify-content-center">
            <div class="col-xl-5 col-xxl-6 d-xl-block text-center"><img class="img-fluid rounded-3 my-3" src="https://dummyimage.com/500x600/343a40/6c757d" alt="..."></div>
            
            <div class="col-lg-8 col-xl-7 col-xxl-6">
                <div class="my-5 text-center text-xl-start">
                    <h1 class="display-5 fw-bolder mb-2">A Bootstrap 5 template for modern businesses</h1>
                    <p class="lead fw-normal mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit!</p>
                    <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                        <a class="btn btn-primary btn-lg px-4 me-sm-3" href="#features">Get Started</a>
                        <a class="btn btn-outline-warning btn-lg px-4" href="#!">Learn More</a>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</section>
{% endblock %}